src/cards/print-control-card/print-control-card-editor.ts, src/cards/print-control-card/print-control-card.ts
- Better TypeScript naming styles except where they were confusing with HA's python naming styles.
- General cleanup to better co-locate code
- Handling a new print starting and a new pick image.
- Disable skip button if print is not in progress.
=> Improvements to card.

src/cards/ams-card/ams-card-editor.ts, src/cards/ams-card/ams-card.ts, src/cards/ams-card/const.ts, src/cards/print-control-card/print-control-card.ts, src/cards/print-status-card/const.ts, src/cards/print-status-card/print-status-card-editor.ts, src/cards/print-status-card/print-status-card.ts, src/const.ts
=> Make the cards show real content in the card picker.

src/cards/print-control-card/print-control-card.ts
=> Update skip to be hidden of 1 or 65+ objects

src/cards/print-control-card/print-control-card.ts
Wasn't allowing for pick_image or skippable_objects to unavailable.
=> Fix disappearing dashboards

src/cards/print-control-card/card.styles.ts, src/cards/print-control-card/print-control-card.ts, src/cards/print-status-card/card.styles.ts, src/cards/print-status-card/print-status-card.ts
- Fix status card resize and re-show behavior to keep entities where they should be instantly.
- Fix handling of short viewports for skip objects popup
- Remove alpha text on both.
- Tweak entity positions.
- Lit-ify the entity html generation.
- Make the light entity a toggle switch.
=> Various card improvements

src/cards/print-status-card/print-status-card.ts
=> Show more info dialog for fans and temperature when clicked

src/cards/print-status-card/print-status-card.ts
=> Forgot to suppress the alternate elements from the UX

src/cards/print-status-card/print-status-card-editor.ts, src/cards/print-status-card/print-status-card.ts
Add custom sensor support to printer status card:
- Temperature
- Humidity
- Power
=> Add custom sensor support to printer status card.

src/cards/print-control-card/card.styles.ts, src/cards/print-control-card/print-control-card.ts, src/cards/print-status-card/print-status-card.ts
Hide cover image if not set.
Switch to HA buttons on control card.
=> Minor fixes

src/cards/print-control-card/card.styles.ts, src/cards/print-control-card/print-control-card.ts
=> Add skip object plate background

src/cards/print-status-card/print-status-card.ts
=> Add glow to fans/temperatures when on

src/cards/ams-card/ams-card.ts, src/cards/ams-card/graphic-ams-card/graphic-ams-card.ts, src/cards/ams-card/vector-ams-card/vector-ams-card.ts
- Replace the asynchronous initialization which is and will be an ongoing bug farm.
- Convert the synchronous initialization via the helpers into the form the specific visuals expect w/ minor modifications since the visuals need to know if the humidity is a custom sensor or not
- Remove all the ? operators that are now unnecessary.
=> Synchronously init ams cards to simplify code and avoid bugs

src/cards/print-control-card/print-control-card.ts
=> Only hid the skip object button if FTP support is turned off

src/cards/print-status-card/print-status-card.ts
=> Switch to hass formatEntityState helper

package-lock.json, package.json, src/cards/ams-card/ams-card.ts, src/cards/ams-card/components/info-bar/info-bar.styles.ts, src/cards/ams-card/components/info-bar/info-bar.ts, src/cards/ams-card/graphic-ams-card/graphic-ams-card.ts, src/cards/ams-card/vector-ams-card/vector-ams-card.styles.ts, src/cards/ams-card/vector-ams-card/vector-ams-card.ts, src/cards/shared-components/ams-popup/ams-popup.styles.ts, src/cards/shared-components/ams-popup/ams-popup.ts, src/cards/shared-components/spool/spool.styles.ts, src/cards/shared-components/spool/spool.ts, src/utils/context.ts, src/utils/helpers.ts
Clicking a spool now shows a popup with more complete information about the spool and Load/Unload buttons.
=> New ams popup

src/cards/spool-card/spool-card.ts
Update the card to use the new lit context stuff.
=> Fix external spool card

src/cards/shared-components/ams-popup/ams-popup.ts, src/utils/helpers.ts
Add the necessary changes to allow a user to select a new color and set it to the AMS. Working end to end.
=> Initial ability to set the filament. Just color for now

src/cards/shared-components/ams-popup/ams-popup.styles.ts, src/cards/shared-components/ams-popup/ams-popup.ts, src/utils/helpers.ts
Hook up filament type/name selects driven by the filament data from the integration.
- [x ] New feature
=> Working filament chooser

src/cards/shared-components/ams-popup/ams-popup.ts
=> Make filament setting exclusive with load/unload buttons

src/cards/print-status-card/print-status-card-editor.ts, src/cards/print-status-card/print-status-card.ts
=> Add config option to control a different light entity

src/cards/ams-card/ams-card.ts, src/cards/print-status-card/print-status-card.ts, src/cards/shared-components/ams-popup/ams-popup.ts, src/cards/spool-card/spool-card.ts, src/utils/context.ts, src/utils/helpers.ts
Update the cards to work nicely with the node red integration.
- Handle the differing entity definitions.
- Hides action buttons that require the integration to support service calls.
=> Adjust for node red

src/cards/print-control-card/card.styles.ts, src/cards/print-control-card/print-control-card.ts
=> Fix control card spacing when card doesn't have much width

src/cards/print-status-card/print-status-card.ts, src/utils/helpers.ts
=> Updates to allow status card to work with nodered.

src/cards/print-status-card/print-status-card.ts
Wasn't mapping all the temperature entities.
=> Fix for node red

src/cards/print-control-card/print-control-card.ts, src/cards/print-status-card/print-status-card.ts, src/utils/helpers.ts
=> Add support for node red to control card

src/cards/print-status-card/a1-screen/a1-screen-card.ts, src/cards/print-status-card/a1-screen/a1-screen-styles.ts
Corrects cropping logic of cover image to maintain aspect ratio
Bug:
Fix:
- x ] I have added/updated tests that prove my fix is effective or that my feature works
=> Image size fix

src/cards/print-control-card/const.ts, src/const.ts
=> Printer fix

src/cards/ams-card/ams-card-editor.ts, src/cards/ams-card/ams-card.ts, src/cards/ams-card/vector-ams-card/vector-ams-card.ts, src/cards/shared-components/spool/spool.ts, src/cards/spool-card/spool-card-editor.ts, src/cards/spool-card/spool-card.ts
Added options to the AMS & Spool card to individually toggle the light reflection/wiggle animations, to allow for disabling the animations if not desired.
I have little to no experience with Lit, but I kept the code style consistent with the existing options so this should hopefully match the required formatting. Also, I have not been able to test this locally as I don't have the time atm.
=> Add ability to toggle active animations on spools

src/cards/ams-card/ams-card-editor.ts, src/cards/ams-card/ams-card.ts, src/cards/shared-components/spool/spool.ts, src/cards/spool-card/spool-card-editor.ts, src/cards/spool-card/spool-card.ts
=> Fix animations back to enabled by default

src/cards/print-status-card/a1-screen/a1-screen-card.ts, src/cards/print-status-card/a1-screen/a1-screen-styles.ts
=> Add position control view

src/cards/print-status-card/a1-screen/a1-screen-card.ts, src/cards/print-status-card/a1-screen/a1-screen-styles.ts
=> Fix label positioning on Safari

src/cards/print-status-card/a1-screen/a1-screen-card.ts, src/cards/shared-components/confirmation-prompt/confirmation-prompt.ts, src/cards/shared-components/skip-objects/index.ts
=> Fix one time only dialogs and cropped image

src/cards/print-status-card/a1-screen/a1-screen-card.ts, src/cards/print-status-card/a1-screen/a1-screen-styles.ts
=> Cleanup move page

src/cards/print-status-card/a1-screen/a1-screen-card.ts
=> Fix remaining time to respect HA settings

src/cards/print-status-card/print-status-card.ts, src/cards/shared-components/entity-provider/index.ts
=> Fix mocked preview for add card UX

src/cards/print-status-card/print-status-card.ts, src/cards/shared-components/entity-provider/index.ts
=> Fix mocked view for add card preview

src/cards/print-status-card/a1-screen/a1-screen-card.ts, src/cards/print-status-card/print-status-card.ts, src/cards/shared-components/entity-provider/index.ts, src/const.ts
Need to use sensors to show state so that we work when the fan controls are unavailable.
=> Fix cards for restricted printer

src/cards/shared-components/ams-popup/ams-popup.styles.ts, src/cards/shared-components/ams-popup/ams-popup.ts
=> Fix ams filament popup viewport sizing

src/cards/print-status-card/a1-screen/a1-screen-card.ts, src/cards/print-status-card/a1-screen/a1-screen-styles.ts
=> Add power button to controls page.

src/cards/ams-card/ams-card-editor.ts, src/cards/ams-card/ams-card.ts, src/cards/ams-card/vector-ams-card/vector-ams-card.styles.ts, src/cards/ams-card/vector-ams-card/vector-ams-card.ts, src/cards/spool-card/spool-card-editor.ts, src/cards/spool-card/spool-card.ts, src/const.ts
=> Fix ams ht and spool card

src/cards/print-status-card/a1-screen/a1-screen-card.ts, src/cards/print-status-card/a1-screen/a1-screen-styles.ts
=> Make AMS selector scrollable if necessary

src/cards/print-status-card/a1-screen/a1-screen-card.ts, src/cards/shared-components/ams-popup/ams-popup.ts, src/cards/shared-components/entity-provider/index.ts, src/cards/shared-components/spool/spool.ts
=> Disable UI in the simple status card that can't work except in developer lan mode

src/cards/print-status-card/a1-screen/a1-screen-card.ts, src/cards/print-status-card/a1-screen/a1-screen-styles.ts
=> Add bed height controls to controls page

src/cards/print-status-card/a1-screen/a1-screen-card.ts, src/cards/print-status-card/a1-screen/a1-screen-styles.ts
=> Add extruder control buttons

src/cards/print-status-card/a1-screen/a1-screen-card.ts, src/utils/helpers.ts
=> Add X1C camera support

src/cards/print-status-card/a1-screen/a1-screen-card.ts, src/utils/helpers.ts
=> Various fixes to latest release

src/cards/print-status-card/a1-screen/a1-screen-card.ts, src/cards/print-status-card/a1-screen/a1-screen-styles.ts, src/cards/print-status-card/print-status-card-editor.ts, src/cards/print-status-card/print-status-card.ts, src/cards/shared-components/spool/spool.ts
=> Switch config over to taking a custom camera entity

src/cards/print-status-card/a1-screen/a1-screen-card.ts
=> Show green rectangle around active AMS

src/cards/print-status-card/a1-screen/a1-screen-card.ts
=> Plumb active state through for external spools

src/cards/spool-card/spool-card-editor.ts, src/cards/spool-card/spool-card.ts
=> Allow spool card to work with AMS spools

src/cards/print-status-card/a1-screen/a1-screen-card.ts
=> Fix skip objects button always being enabled

src/cards/print-status-card/a1-screen/a1-screen-card.ts, src/cards/shared-components/entity-provider/index.ts
=> Add support for image camera

src/cards/print-status-card/a1-screen/a1-screen-card.ts
=> Fix image camera when dead 'camera' camera entity is still hanging around.

src/cards/print-status-card/a1-screen/a1-screen-card.ts
=> Fix handling of stale image camera

src/cards/shared-components/print-history-popup/print-history-popup.styles.ts
=> Fix mobile screen layout

src/cards/print-status-card/print-status-card.ts
=> Fix remaining time on graphical card

src/cards/shared-components/print-history-popup/print-history-popup.styles.ts, src/cards/shared-components/print-history-popup/print-history-popup.ts
=> Add total cache size to popup

src/cards/print-status-card/a1-screen/a1-screen-card.ts
=> Fix displayed unit on simple status card

src/cards/ams-card/ams-card-editor.ts, src/cards/ams-card/ams-card.ts, src/cards/ams-card/components/info-bar/info-bar.styles.ts, src/cards/ams-card/components/info-bar/info-bar.ts, src/cards/ams-card/graphic-ams-card/graphic-ams-card.ts, src/cards/ams-card/vector-ams-card/vector-ams-card.styles.ts, src/cards/spool-card/spool-card-editor.ts, src/cards/spool-card/spool-card.styles.ts, src/cards/spool-card/spool-card.ts, src/utils/helpers.ts
=> Updates to ams visuals
